#!/bin/bash

NAME=obe
OBE=/usr/bin/obecli

screen -d -m -S $NAME nice -n -10 $OBE
sleep 1
screen -p 0 -S $NAME -X stuff $'set input decklink\012'
screen -p 0 -S $NAME -X stuff $'set input opts card-idx=1\012'
screen -p 0 -S $NAME -X stuff $'set input opts video-format=1080i50\012'
screen -p 0 -S $NAME -X stuff $'set input opts video-connection=sdi\012'
screen -p 0 -S $NAME -X stuff $'set input opts audio-connection=embedded\012'
screen -p 0 -S $NAME -X stuff $'probe input\012'
sleep 2
screen -p 0 -S $NAME -X stuff $'set stream opts 0:pid=1000,vbv-maxrate=4600,vbv-bufsize=4600,bitrate=4600,keyint=24,bframes=3,threads=4,format=avc,profile=high,level=4\012'
screen -p 0 -S $NAME -X stuff $'set stream opts 1:pid=1001,bitrate=64,format=aac,aac-profile=he-aac-v1,aac-encap=adts\012'
screen -p 0 -S $NAME -X stuff $'add stream 2:type=audio\012'
screen -p 0 -S $NAME -X stuff $'set stream opts 2:pid=1002,bitrate=192,format=mp2\012'
screen -p 0 -S $NAME -X stuff $'set muxer opts cbr=1,pmt-pid=100,ts-muxrate=5200000,ts-type=dvb,pcr-period=20,pat-period=100\012'
screen -p 0 -S $NAME -X stuff $'set output udp\012'
screen -p 0 -S $NAME -X stuff $'set output opts target=udp://232.40.3.1:2000?ttl=20\012'
screen -p 0 -S $NAME -X stuff $'start\012'

